BulkyBook/Areas/Admin/Controllers/CategoryController.cs
using BulkyBook1.DataAccess.Repository.IRepository;
using BulkyBook1.Models;
using BulkyBook1.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBook.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _UnitOfWork;

        public CategoryController(IUnitOfWork db)
        {
            _UnitOfWork = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> objCategoryList = _UnitOfWork.Category.GetAll();
            return View(objCategoryList);
        }

        //Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "The DisplayOrder cannot exactly match the Name");
            }
            if (ModelState.IsValid)
            {
                _UnitOfWork.Category.Add(obj);
                _UnitOfWork.Save();
                TempData["success"] = "Category is created successfuly";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var CategoryFromDb = _UnitOfWork.Category.GetFirstOrDefault(x => x.Id == id);
            if (CategoryFromDb == null)
                return NotFound();
            return View(CategoryFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "The DisplayOrder cannot exactly match the Name");
            }
            if (ModelState.IsValid)
            {
                _UnitOfWork.Category.Update(obj);
                _UnitOfWork.Save();
                TempData["success"] = "Category is" +
                    "updated successfuly";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var CategoryFromDb = _UnitOfWork.Category.GetFirstOrDefault(x => x.Id.Equals(id));
            if (CategoryFromDb == null)
                return NotFound();
            return View(CategoryFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _UnitOfWork.Category.GetFirstOrDefault(x => x.Id.Equals(id));
            if (obj == null)
                return NotFound();

            _UnitOfWork.Category.Remove(obj);
            _UnitOfWork.Save();
            TempData["success"] = "Category is deleted successfuly";
            return RedirectToAction("Index");
        }
    }
}

BulkyBook/Areas/Admin/Controllers/CompanyController.cs
using BulkyBook1.DataAccess.Repository.IRepository;
using BulkyBook1.Models;
using BulkyBook1.Models.ViewModels;
using BulkyBook1.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkyBook.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _UnitOfWork;
        

        public CompanyController(IUnitOfWork db)
        {
            _UnitOfWork = db;
        }

        public IActionResult Index()
        {
            //IEnumerable<Product> objProductList = _UnitOfWork.Product.GetAll();
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            Company company = new();
            
            if (id == null || id == 0)
            {
                return View(company);
            }
            else
            {
                company = _UnitOfWork.Company.GetFirstOrDefault(p => p.Id == id);
                return View(company);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company obj)
        {
            if(ModelState.IsValid)
            {
                if (obj.Id == 0)
                {
                    _UnitOfWork.Company.Add(obj);
                    TempData["success"] = "Product is created successfuly";
                }
                    
                else
                {
                    _UnitOfWork.Company.Update(obj);
                    TempData["success"] = "Product is update successfuly";
                }
                   
                _UnitOfWork.Save();
               
                return RedirectToAction("Index");
            }
            return View(obj);
        }



        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            var companyList = _UnitOfWork.Company.GetAll();
            return Json(new { data = companyList });
        }

        //POST
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _UnitOfWork.Company.GetFirstOrDefault(x => x.Id.Equals(id));
            if (obj == null)
                return Json(new { success = false, message = "Error while Deleting" });

            //Must delete Image before detele product
             
            _UnitOfWork.Company.Remove(obj);
            _UnitOfWork.Save();
            TempData["success"] = "Product is deleted successfuly";
            return Json(new { success = true, message = "Delete successful" });
        }

        #endregion API CALLS
    }
}

BulkyBook/Areas/Admin/Controllers/CoverTypeController.cs
using BulkyBook1.DataAccess.Repository.IRepository;
using BulkyBook1.Models;
using BulkyBook1.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBook.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _UnitOfWork;

        public CoverTypeController(IUnitOfWork db)
        {
            _UnitOfWork = db;
        }

        public IActionResult Index()
        {
            IEnumerable<CoverType> objCoverTypeList = _UnitOfWork.CoverType.GetAll();
            return View(objCoverTypeList);
        }

        //Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {
            if (ModelState.IsValid)
            {
                _UnitOfWork.CoverType.Add(obj);
                _UnitOfWork.Save();
                TempData["success"] = "CoverType is created successfuly";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var CoverTypeFromDb = _UnitOfWork.CoverType.GetFirstOrDefault(x => x.Id == id);
            if (CoverTypeFromDb == null)
                return NotFound();
            return View(CoverTypeFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType obj)
        {
            if (ModelState.IsValid)
            {
                _UnitOfWork.CoverType.Update(obj);
                _UnitOfWork.Save();
                TempData["success"] = "CoverType is updated successfuly";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var CoverTypeFromDb = _UnitOfWork.CoverType.GetFirstOrDefault(x => x.Id.Equals(id));
            if (CoverTypeFromDb == null)
                return NotFound();
            return View(CoverTypeFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _UnitOfWork.CoverType.GetFirstOrDefault(x => x.Id.Equals(id));
            if (obj == null)
                return NotFound();

            _UnitOfWork.CoverType.Remove(obj);
            _UnitOfWork.Save();
            TempData["success"] = "CoverType is deleted successfuly";
            return RedirectToAction("Index");
        }
    }
}

BulkyBook/Areas/Admin/Controllers/ProductController.cs
using BulkyBook1.DataAccess.Repository.IRepository;
using BulkyBook1.Models.ViewModels;
using BulkyBook1.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkyBook.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _UnitOfWork;
        private IWebHostEnvironment _hostEnvironment;

        public ProductController(IUnitOfWork db, IWebHostEnvironment hostEnvironment)
        {
            _UnitOfWork = db;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            //IEnumerable<Product> objProductList = _UnitOfWork.Product.GetAll();
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            ProductVM productVM = new()
            {
                Product = new(),
                CategoryList = _UnitOfWork.Category.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                CoverTypeList = _UnitOfWork.CoverType.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                })
            };
            //Product product = new();
            //IEnumerable<SelectListItem> CategoryList = _UnitOfWork.Category.GetAll().Select(
            //    u => new SelectListItem
            //    {
            //        Text = u.Name,
            //        Value = u.Id.ToString()
            //    });
            //IEnumerable<SelectListItem> CoverTypeList = _UnitOfWork.CoverType.GetAll().Select(
            //    u => new SelectListItem
            //    {
            //        Text = u.Name,
            //        Value = u.Id.ToString()
            //    });
            if (id == null || id == 0)
            {
                //create product
                //ViewBag.CategoryList = CategoryList;
                //ViewData["CoverTypeList"] = CoverTypeList;
                return View(productVM);
            }
            else
            {
                productVM.Product = _UnitOfWork.Product.GetFirstOrDefault(p => p.Id == id);
                return View(productVM);
                //update product
            }
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM obj, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                //WebRootPath:Nhận hoặc đặt đường dẫn tuyệt đối đến thư mục chứa các tệp nội dung ứng dụng có thể phục vụ web.
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    //Tạo tên file ảnh
                    string fileName = Guid.NewGuid().ToString();
                    //Lấy đường dẫn để lưu file wwwRootPath: đường dẫn gốc + images\products = folder
                    var uploads = Path.Combine(wwwRootPath, @"images\products");
                    //Láy đuôi file ảnh
                    var extension = Path.GetExtension(file.FileName);

                    if (obj.Product.ImageURL != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.Product.ImageURL.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    obj.Product.ImageURL = @"\images\products\" + fileName + extension;
                }

                if (obj.Product.Id == 0)
                    _UnitOfWork.Product.Add(obj.Product);   
                else
                    _UnitOfWork.Product.Update(obj.Product);
                
                _UnitOfWork.Save();
                TempData["success"] = "Product is created successfuly";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //public IActionResult Delete(int? id)
        //{
        //    if (id == null || id == 0)
        //    {
        //        return NotFound();
        //    }
        //    var ProductFromDb = _UnitOfWork.Product.GetFirstOrDefault(x => x.Id.Equals(id));
        //    if (ProductFromDb == null)
        //        return NotFound();
        //    return View(ProductFromDb);
        //}

        
        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            var productList = _UnitOfWork.Product.GetAll(includeProperties: "Category,CoverType");
            return Json(new { data = productList });
        }

        //POST
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _UnitOfWork.Product.GetFirstOrDefault(x => x.Id.Equals(id));
            if (obj == null)
                return Json(new { success = false, message = "Error while Deleting" });

            //Must delete Image before detele product
            var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageURL.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }

            _UnitOfWork.Product.Remove(obj);
            _UnitOfWork.Save();
            TempData["success"] = "Product is deleted successfuly";
            return Json(new { success = true, message = "Delete successful" });
        }

        #endregion API CALLS
    }
}

BulkyBook/Views/Shared/_Layout.cshtml
@using BulkyBook1.Utility
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BulkyBook.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Book</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor02">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link" asp-area="Customer"  asp-controller="Home" asp-action="Index">Home</a>
            </li>
            @if(User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee))
            {
             <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Management</a>
              <div class="dropdown-menu">
                <a class="dropdown-item" asp-area="Admin"  asp-controller="Category" asp-action="index">Category</a>
                <a class="dropdown-item" asp-area="Admin"  asp-controller="CoverType" asp-action="index">Cover Type</a>
                <a class="dropdown-item" asp-area="Admin"  asp-controller="Product" asp-action="index">Product</a>
                <a class="dropdown-item" asp-area="Admin"  asp-controller="Company" asp-action="index">Company</a>
                <a class="dropdown-item" asp-area="Admin"  asp-controller="Order" asp-action="index">Order</a>

                <div class="dropdown-divider"></div>
              </div>
            </li>   
            }
            

            <li class="nav-item" >
                <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                    <i class="bi bi-cart"></i>
                </a>
            </li>
          </ul>
          <partial name="_LoginPartial" />
         @* <form class="d-flex">
            <input class="form-control me-sm-2" type="text" placeholder="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
          </form>*@
        </div>
      </div>
  </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-dark">
        <div class="container">
            &copy; 2022 - BulkyBook - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" ></script>
      <script src="https://cdn.tiny.cloud/1/42wb1h7qzxxqi13yugisnalzo2t6n18sv8tcjg9q7ij2bu2c/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyBook/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js" ></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" ></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');  
    </script>
}
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" ></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');  
    </script>
}